# Generated by Django 3.2.24 on 2024-05-27 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stuapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='branch',
            new_name='field_of_study',
        ),
    ]
